# Generated by Django 5.0.6 on 2026-09-02 18:22

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaCardapio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, unique=True)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('icone', models.CharField(default='🐟', help_text='Emoji usado como ícone no cardápio (tema de pescaria)', max_length=10)),
            ],
            options={
                'verbose_name': 'Categoria do cardápio',
                'verbose_name_plural': 'Categorias do cardápio',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('capacidade', models.PositiveSmallIntegerField(default=4)),
                ('ativa', models.BooleanField(default=True)),
                ('localizacao', models.CharField(blank=True, help_text='Ex.: Lago 1, Deck coberto, Varanda', max_length=100)),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('papel', models.CharField(choices=[('cliente', 'Cliente'), ('garcom', 'Garçom / Atendente'), ('cozinha', 'Cozinha'), ('gerente', 'Gerente')], default='cliente', max_length=10)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('preferencia_alto_contraste', models.BooleanField(default=False)),
                ('preferencia_fonte_grande', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('enviada', 'Enviada à cozinha'), ('em_preparo', 'Em preparo'), ('pronta', 'Pronta para entrega'), ('entregue', 'Entregue'), ('fechada', 'Fechada / Paga'), ('cancelada', 'Cancelada')], default='aberta', max_length=12)),
                ('observacoes', models.TextField(blank=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('pago', models.BooleanField(default=False)),
                ('pago_em', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comandas', to=settings.AUTH_USER_MODEL)),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comandas', to='core.mesa')),
            ],
            options={
                'verbose_name': 'Comanda',
                'verbose_name_plural': 'Comandas',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemCardapio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='cardapio/')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('unidade', models.CharField(choices=[('un', 'Unidade'), ('kg', 'Quilo'), ('porcao', 'Porção')], default='un', max_length=10)),
                ('disponivel', models.BooleanField(default=True)),
                ('eh_pescado_no_local', models.BooleanField(default=False, help_text='Marque para peixes pescados pelo próprio cliente no local')),
                ('tempo_preparo_min', models.PositiveSmallIntegerField(default=15)),
                ('imagem_alt', models.CharField(blank=True, help_text='Descrição da imagem para leitores de tela', max_length=200)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='core.categoriacardapio')),
            ],
            options={
                'verbose_name': 'Item do cardápio',
                'verbose_name_plural': 'Itens do cardápio',
                'ordering': ['categoria__ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ItemComanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('observacoes', models.CharField(blank=True, max_length=200)),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.comanda')),
                ('item_cardapio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.itemcardapio')),
            ],
            options={
                'verbose_name': 'Item da comanda',
                'verbose_name_plural': 'Itens da comanda',
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mercado_pago_id', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Aguardando pagamento'), ('in_process', 'Em processamento'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qr_code', models.TextField(blank=True)),
                ('qr_code_base64', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='core.comanda')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
