# Generated by Django 5.0.6 on 2026-09-08 21:09

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoEstabelecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Pesque & Pague', max_length=120)),
                ('descricao_restaurante', models.TextField(blank=True)),
                ('descricao_pesque_pague', models.TextField(blank=True)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('whatsapp', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('endereco', models.CharField(blank=True, max_length=240)),
                ('link_mapa', models.URLField(blank=True)),
                ('aviso_importante', models.CharField(blank=True, max_length=240)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração do estabelecimento',
                'verbose_name_plural': 'Configuração do estabelecimento',
            },
        ),
        migrations.CreateModel(
            name='EspeciePeixe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('preco_quilo', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('disponivel', models.BooleanField(default=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='pesca/especies/')),
                ('imagem_alt', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Espécie de peixe',
                'verbose_name_plural': 'Espécies de peixe',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='HorarioFuncionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], unique=True)),
                ('abre_as', models.TimeField(blank=True, null=True)),
                ('fecha_as', models.TimeField(blank=True, null=True)),
                ('fechado', models.BooleanField(default=False)),
                ('observacao', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'verbose_name': 'Horário de funcionamento',
                'verbose_name_plural': 'Horários de funcionamento',
                'ordering': ['dia_semana'],
            },
        ),
        migrations.CreateModel(
            name='ImagemGaleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('restaurante', 'Restaurante'), ('pesca', 'Pesque-pague')], max_length=15)),
                ('titulo', models.CharField(blank=True, max_length=120)),
                ('imagem', models.ImageField(upload_to='galeria/')),
                ('imagem_alt', models.CharField(max_length=200)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Imagem da galeria',
                'verbose_name_plural': 'Imagens da galeria',
                'ordering': ['area', 'ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LagoPesca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('modalidade', models.CharField(choices=[('pesque_pague', 'Pesque-pague'), ('esportiva', 'Pesca esportiva'), ('mista', 'Pesque-pague e esportiva')], max_length=20)),
                ('valor_diaria', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('capacidade', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('disponivel', models.BooleanField(default=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='pesca/lagos/')),
                ('imagem_alt', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Lago de pesca',
                'verbose_name_plural': 'Lagos de pesca',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='RegraPesca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('descricao', models.TextField()),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Regra de pesca',
                'verbose_name_plural': 'Regras de pesca',
                'ordering': ['ordem', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='ServicoPesca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('servico', 'Serviço'), ('equipamento', 'Equipamento')], default='servico', max_length=15)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('disponivel', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Serviço de pesca',
                'verbose_name_plural': 'Serviços de pesca',
                'ordering': ['tipo', 'nome'],
            },
        ),
        migrations.AlterField(
            model_name='comanda',
            name='status',
            field=models.CharField(choices=[('aberta', 'Aberta'), ('enviada', 'Enviada à cozinha'), ('em_preparo', 'Em preparo'), ('pronta', 'Pronta para entrega'), ('entregue', 'Entregue'), ('fechada', 'Fechada'), ('cancelada', 'Cancelada')], default='aberta', max_length=12),
        ),
        migrations.CreateModel(
            name='RegistroPesca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pescador_nome', models.CharField(max_length=120)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('modalidade', models.CharField(choices=[('pesque_pague', 'Pesque-pague'), ('esportiva', 'Pesca esportiva'), ('diaria', 'Diária')], max_length=20)),
                ('status', models.CharField(choices=[('aberto', 'Em andamento'), ('encerrado', 'Encerrado'), ('cancelado', 'Cancelado')], default='aberto', max_length=12)),
                ('valor_entrada', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('observacoes', models.TextField(blank=True)),
                ('entrada_em', models.DateTimeField(auto_now_add=True)),
                ('saida_em', models.DateTimeField(blank=True, null=True)),
                ('lago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='core.lagopesca')),
                ('responsavel_entrada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_pesca_abertos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de pesca',
                'verbose_name_plural': 'Registros de pesca',
                'ordering': ['-entrada_em'],
            },
        ),
        migrations.CreateModel(
            name='ImpressaoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('comanda_cliente', 'Comanda do cliente'), ('cozinha', 'Via da cozinha'), ('balcao', 'Via do balcão'), ('resumo_mesa', 'Resumo da mesa'), ('registro_pesca', 'Registro do pesque-pague'), ('comprovante_pesca', 'Comprovante do pesque-pague'), ('fechamento', 'Fechamento da operação')], max_length=24)),
                ('status', models.CharField(choices=[('gerado', 'Gerado'), ('solicitado', 'Solicitado para impressão'), ('reimpresso', 'Reimpresso')], default='gerado', max_length=12)),
                ('quantidade_solicitacoes', models.PositiveIntegerField(default=0)),
                ('gerado_em', models.DateTimeField(auto_now_add=True)),
                ('ultima_solicitacao_em', models.DateTimeField(blank=True, null=True)),
                ('comanda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos_impressao', to='core.comanda')),
                ('gerado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_gerados', to=settings.AUTH_USER_MODEL)),
                ('registro_pesca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos_impressao', to='core.registropesca')),
            ],
            options={
                'verbose_name': 'Documento para impressão',
                'verbose_name_plural': 'Documentos para impressão',
                'ordering': ['-gerado_em'],
            },
        ),
        migrations.CreateModel(
            name='CapturaPesca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_kg', models.DecimalField(decimal_places=3, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('preco_quilo', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('observacoes', models.CharField(blank=True, max_length=200)),
                ('registrado_em', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capturas_registradas', to=settings.AUTH_USER_MODEL)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capturas', to='core.especiepeixe')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capturas', to='core.registropesca')),
            ],
            options={
                'verbose_name': 'Pesagem de peixe',
                'verbose_name_plural': 'Pesagens de peixe',
                'ordering': ['registrado_em'],
            },
        ),
        migrations.AddConstraint(
            model_name='impressaodocumento',
            constraint=models.UniqueConstraint(condition=models.Q(('comanda__isnull', False)), fields=('tipo_documento', 'comanda'), name='impressao_tipo_comanda_unica'),
        ),
        migrations.AddConstraint(
            model_name='impressaodocumento',
            constraint=models.UniqueConstraint(condition=models.Q(('registro_pesca__isnull', False)), fields=('tipo_documento', 'registro_pesca'), name='impressao_tipo_pesca_unica'),
        ),
    ]
