# Generated by Django 5.2.17 on 2026-09-11 15:12

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import Count
from django.utils import timezone


def normalizar_comandas_duplicadas(apps, schema_editor):
    Comanda = apps.get_model("core", "Comanda")
    ativos = ["aberta", "enviada", "em_preparo", "pronta", "entregue"]
    agora = timezone.now()

    mesas = (
        Comanda.objects.filter(status__in=ativos)
        .values("mesa_id")
        .annotate(total=Count("id"))
        .filter(total__gt=1)
    )
    for grupo in mesas:
        ids_excedentes = list(
            Comanda.objects.filter(mesa_id=grupo["mesa_id"], status__in=ativos)
            .order_by("-atualizada_em", "-id")
            .values_list("id", flat=True)[1:]
        )
        Comanda.objects.filter(id__in=ids_excedentes).update(
            status="cancelada",
            cancelada_em=agora,
            motivo_cancelamento="Duplicidade anterior corrigida na migração de integridade.",
        )

    clientes = (
        Comanda.objects.filter(status="aberta", cliente_id__isnull=False)
        .values("cliente_id")
        .annotate(total=Count("id"))
        .filter(total__gt=1)
    )
    for grupo in clientes:
        ids_excedentes = list(
            Comanda.objects.filter(cliente_id=grupo["cliente_id"], status="aberta")
            .order_by("-atualizada_em", "-id")
            .values_list("id", flat=True)[1:]
        )
        Comanda.objects.filter(id__in=ids_excedentes).update(
            status="cancelada",
            cancelada_em=agora,
            motivo_cancelamento="Duplicidade anterior corrigida na migração de integridade.",
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_configuracaoestabelecimento_especiepeixe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisicaoIdempotente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operacao', models.CharField(max_length=100)),
                ('chave', models.CharField(max_length=64)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='comanda',
            name='cancelada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comanda',
            name='cancelada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comandas_canceladas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comanda',
            name='motivo_cancelamento',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='especiepeixe',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.caminho_imagem),
        ),
        migrations.AlterField(
            model_name='imagemgaleria',
            name='imagem',
            field=models.ImageField(upload_to=core.models.caminho_imagem),
        ),
        migrations.AlterField(
            model_name='itemcardapio',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.caminho_imagem),
        ),
        migrations.AlterField(
            model_name='lagopesca',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.caminho_imagem),
        ),
        migrations.RunPython(normalizar_comandas_duplicadas, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='comanda',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['aberta', 'enviada', 'em_preparo', 'pronta', 'entregue'])), fields=('mesa',), name='comanda_ativa_unica_por_mesa'),
        ),
        migrations.AddConstraint(
            model_name='comanda',
            constraint=models.UniqueConstraint(condition=models.Q(('cliente__isnull', False), ('status', 'aberta')), fields=('cliente',), name='comanda_aberta_unica_por_cliente'),
        ),
        migrations.AddField(
            model_name='requisicaoidempotente',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisicoes_idempotentes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='requisicaoidempotente',
            index=models.Index(fields=['criada_em'], name='core_requis_criada__34818d_idx'),
        ),
        migrations.AddConstraint(
            model_name='requisicaoidempotente',
            constraint=models.UniqueConstraint(fields=('usuario', 'operacao', 'chave'), name='requisicao_idempotente_unica'),
        ),
    ]
