# Generated by Django 5.2.17 on 2026-09-15 01:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_promote_tayllon_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoComanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_nome', models.CharField(blank=True, max_length=150)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('acao', models.CharField(max_length=50)),
                ('dados', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['criado_em', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('recebido', 'Recebido'), ('preparando', 'Em preparação'), ('pronto', 'Pronto'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], default='recebido', max_length=16)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cancelado_em', models.DateTimeField(null=True)),
                ('motivo_cancelamento', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['criado_em', 'id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='comanda',
            name='comanda_ativa_unica_por_mesa',
        ),
        migrations.AddField(
            model_name='comanda',
            name='acrescimo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='comanda',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='comanda',
            name='fechada_em',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='comanda',
            name='fechada_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos_fechados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comanda',
            name='identificacao',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='comanda',
            name='responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos_abertos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comanda',
            name='subtotal_fechamento',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='comanda',
            name='total_fechamento',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='comanda',
            name='versao',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itemcomanda',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='itemcomanda',
            name='cancelado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itemcomanda',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='itemcomanda',
            name='criado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemcomanda',
            name='motivo_cancelamento',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='itemcomanda',
            name='nome_registrado',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='forma',
            field=models.CharField(choices=[('dinheiro', 'Dinheiro'), ('pix', 'PIX'), ('debito', 'Cartão de débito'), ('credito', 'Cartão de crédito')], default='pix', max_length=20),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='origem',
            field=models.CharField(choices=[('online', 'Online'), ('manual', 'Presencial')], default='online', max_length=10),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='registrado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requisicaoidempotente',
            name='assinatura',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='requisicaoidempotente',
            name='resultado_id',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='mesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comandas', to='core.mesa'),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='status',
            field=models.CharField(choices=[('aberta', 'Aberta'), ('enviada', 'Enviada à cozinha'), ('em_preparo', 'Em preparo'), ('pronta', 'Pronta para entrega'), ('entregue', 'Entregue'), ('fechada', 'Fechada'), ('cancelada', 'Cancelada'), ('atendimento', 'Em atendimento'), ('aguardando_pagamento', 'Aguardando pagamento')], default='aberta', max_length=24),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='mercado_pago_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='papel',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('garcom', 'Garçom / Atendente'), ('cozinha', 'Cozinha'), ('gerente', 'Gerente'), ('caixa', 'Caixa')], default='cliente', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='comanda',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['aberta', 'enviada', 'em_preparo', 'pronta', 'entregue', 'atendimento', 'aguardando_pagamento'])), fields=('mesa',), name='comanda_ativa_unica_por_mesa'),
        ),
        migrations.AddField(
            model_name='eventocomanda',
            name='comanda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='core.comanda'),
        ),
        migrations.AddField(
            model_name='eventocomanda',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pedido',
            name='comanda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='core.comanda'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemcomanda',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='core.pedido'),
        ),
    ]
