# Generated by Django 5.2.17 on 2026-09-16 02:06

import core.models
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_preservar_pedidos_existentes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaAdministrativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_nome', models.CharField(max_length=150)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('acao', models.CharField(max_length=50)),
                ('entidade', models.CharField(max_length=80)),
                ('identificador', models.CharField(max_length=80)),
                ('dados', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-criado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MetaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='MovimentoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo', models.CharField(choices=[('pedido', 'Pedido'), ('cancelamento', 'Cancelamento'), ('ajuste', 'Ajuste manual'), ('alteracao', 'Alteração de pedido')], max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('motivo', models.CharField(max_length=500)),
            ],
            options={
                'ordering': ['-criado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('telefone', models.CharField(max_length=30)),
                ('data', models.DateField(db_index=True)),
                ('horario', models.TimeField()),
                ('pessoas', models.PositiveSmallIntegerField()),
                ('observacao', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada / recusada'), ('finalizada', 'Finalizada')], default='pendente', max_length=12)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('chave', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'ordering': ['-data', 'horario', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SessaoCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aberta_em', models.DateTimeField(auto_now_add=True)),
                ('fechada_em', models.DateTimeField(blank=True, null=True)),
                ('valor_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('dinheiro_contado', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('observacoes', models.CharField(blank=True, max_length=500)),
                ('terminal', models.CharField(default='principal', editable=False, max_length=20)),
            ],
            options={
                'ordering': ['-aberta_em', '-id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='comanda',
            name='comanda_ativa_unica_por_mesa',
        ),
        migrations.RemoveConstraint(
            model_name='impressaodocumento',
            name='impressao_tipo_comanda_unica',
        ),
        migrations.AddField(
            model_name='comanda',
            name='vinculo_token',
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='configuracaoestabelecimento',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.caminho_imagem),
        ),
        migrations.AddField(
            model_name='configuracaoestabelecimento',
            name='descricao_atrativos',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='configuracaoestabelecimento',
            name='descricao_inicio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='configuracaoestabelecimento',
            name='descricao_piscinas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='configuracaoestabelecimento',
            name='impressora_cozinha',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='configuracaoestabelecimento',
            name='papel_cozinha',
            field=models.CharField(choices=[('80mm', '80 mm'), ('58mm', '58 mm')], default='80mm', max_length=4),
        ),
        migrations.AddField(
            model_name='impressaodocumento',
            name='confirmado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='impressaodocumento',
            name='detalhe_falha',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='impressaodocumento',
            name='pedido',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='impressao', to='core.pedido'),
        ),
        migrations.AddField(
            model_name='itemcardapio',
            name='controla_estoque',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itemcardapio',
            name='destaque',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itemcardapio',
            name='estoque_atual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='itemcardapio',
            name='estoque_minimo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='itemcomanda',
            name='estoque_baixado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='imagemgaleria',
            name='area',
            field=models.CharField(choices=[('restaurante', 'Restaurante'), ('pesca', 'Pesque-pague'), ('piscina', 'Piscinas'), ('atrativos', 'Atrativos')], max_length=15),
        ),
        migrations.AlterField(
            model_name='impressaodocumento',
            name='status',
            field=models.CharField(choices=[('gerado', 'Gerado'), ('solicitado', 'Solicitado para impressão'), ('reimpresso', 'Reimpresso'), ('pendente', 'Pendente'), ('impresso', 'Impresso (confirmado pelo operador)'), ('falha', 'Falha')], default='gerado', max_length=12),
        ),
        migrations.AddConstraint(
            model_name='impressaodocumento',
            constraint=models.UniqueConstraint(condition=models.Q(('comanda__isnull', False), ('pedido__isnull', True)), fields=('tipo_documento', 'comanda'), name='impressao_tipo_comanda_unica'),
        ),
        migrations.AddConstraint(
            model_name='itemcardapio',
            constraint=models.CheckConstraint(condition=models.Q(('estoque_atual__gte', 0)), name='produto_estoque_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='itemcardapio',
            constraint=models.CheckConstraint(condition=models.Q(('estoque_minimo__gte', 0)), name='produto_minimo_nao_negativo'),
        ),
        migrations.AddField(
            model_name='auditoriaadministrativa',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimentoestoque',
            name='pedido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.pedido'),
        ),
        migrations.AddField(
            model_name='movimentoestoque',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos_estoque', to='core.itemcardapio'),
        ),
        migrations.AddField(
            model_name='movimentoestoque',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sessaocaixa',
            name='aberta_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caixas_abertos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sessaocaixa',
            name='fechada_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caixas_fechados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='caixa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='core.sessaocaixa'),
        ),
        migrations.AddConstraint(
            model_name='sessaocaixa',
            constraint=models.UniqueConstraint(condition=models.Q(('fechada_em__isnull', True)), fields=('terminal',), name='um_caixa_aberto_por_terminal'),
        ),
    ]
