# Generated by Django 5.2.17 on 2026-09-16 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auditoriaadministrativa_metadiaria_movimentoestoque_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivoMidia',
            fields=[
                ('nome', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('conteudo', models.BinaryField()),
                ('mime', models.CharField(max_length=30)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
