# Generated by Django 5.2.17 on 2026-09-27 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_fotos_cardapio_faltantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaoestabelecimento',
            name='nome',
            field=models.CharField(default='Clube Imperial', max_length=120),
        ),
    ]
